### PR TITLE
#60, #96, #106, #113, #114, #115, #117, #118, #120, #123 - removed interpretation of number as a separate inteface

### PR DESCRIPTION
**Pull request by biboran**
As per #60
* Removed `NumberScalar`. Replaced relatively small numbers with `IntegerScalar`. Almost all ethereum numbers are now represented as `BytesScalar`
* Added basic mathematical operations on `IntegerScalar` and numbers represented as `BytesScalar`

As per #96
* Updated relevant comments to Apple style markup

As per #106
* Added response verification as a `VerifiedNetwork` decorator

As per #113 
* Replaced top level acl rule with a class declaration acl

As per #114 
* Updated all licenses

As per #115 
* Added `PrivateKeyAddress` to access address of the `PrivateKey` declaratively

As per #117 
* Replaced `message` and `hashFunction` with a `digest` ctor. It's now expected that `digest` is a valid 32 bytes sequence.

As per #118 
* Removed EOS test. We should create a mainnet public account, put a bit of eth there, verify it for an exact amount and wait until someone tips; then adjust and repeat.

As per #120 
* Added a ctor with a `sender` as a depedency

As per #123 
* Fixed a bug in `QuantityParameter` that encoded 0 as `0x` instead of `0x0`

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#125](https://github.com/blockstoreapp/web3swift/issues/125) is now in scope, role is `REV`

**Comment by biboran** [comment]
It seems like the coverage is underreported because of http://www.openradar.me/40734694

**Comment by 0crat** [comment]
Job `gh:blockstoreapp/web3swift#125` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#125](https://github.com/blockstoreapp/web3swift/issues/125) is now out of scope

**Pull request merged**
